config/routes.rb
Rails.application.routes.draw do

  get 'about_us', to: 'pages#AboutUs'

  get 'contact', to: 'contact#new', as: 'new_contact'
  post 'contact', to: 'contact#create', as: 'create_contact'

  # get 'custom_services', to: 'pages#CustomServices'

  get 'privacy_policy', to: 'pages#PrivacyPolicy'
  get 'harrassment_policy', to:'pages#HarrassmentPolicy'

  get 'cnc_machining', to: 'pages#CncMachining'

  get 'production_equipment', to: 'pages#ProductionEquipment'

  root to: 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact
	include ActiveModel::Model
	attr_accessor :name, :email, :job_position, :company_name, :phone, :body
	validates :name, :email, :job_position, :company_name, :phone, :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SeoKeywords
  include CustomTabNames
  include CopyrightGenerator
end

app/controllers/concerns/copyright_generator.rb
module CopyrightGenerator 
  extend ActiveSupport::Concern

  included do 
    before_action :set_copyright
  end
  
  
  def set_copyright
    @copyright = GaelenCopyright::Renderer.copyright "Boman Technologies"
  end
  
  module GaelenCopyright
    class Renderer
      def self.copyright msg
        "&copy; #{Time.now.year} | #{msg}".html_safe
      end
    end
  end
end

app/controllers/concerns/custom_tab_names.rb
module CustomTabNames
  extend ActiveSupport::Concern

  included do 
    before_action :default_title
  end

  def default_title
    @page_title = "Boman Technologies | Home"
  end
end

app/controllers/concerns/seo_keywords.rb
module SeoKeywords
  extend ActiveSupport::Concern

  included do 
    before_action :seo_keywords
  end

  def seo_keywords
    @seo_keywords = "Boman Technologies,
                    Boman,
                    Bowman Technologies,
                    Bowman, 
                    Boman Technology,
                    Contact Boman,
                    Engineering, 
                    Precision, 
                    Metal, 
                    Machining, 
                    Machine, 
                    Precision-made, 
                    USA made, 
                    American Made, 
                    Engineers, 
                    Mandrel,
                    Machine Shop,
                    Milford,
                    Connecticut,
                    Miyano,
                    Miyano Engineering,
                    Drilling,
                    Drilling Parts,
                    Quality"
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
	def new
		@contact = Contact.new
		@page_title = "Boman | Start a Partnership"
	end

	def create
		@contact = Contact.new contact_params

		if @contact.valid? && verify_recaptcha
			ContactMailer.contact_us(@contact).deliver_now
			redirect_to new_contact_url, notice: "Message sent, we will contact you soon. Thank you!"
		else
			flash.delete(:recaptcha_error)
			flash[:error] = "Please check the recaptcha"
			render :new
		end
	end

	private

	def contact_params
		params.require(:contact).permit(:name, :email, :job_position, :company_name, :phone, :body)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def Homepage
  end

  def AboutUs
    @page_title = "Boman | About our Family"
  end

  def CustomServices

  end

  def PrivacyPolicy
    @page_title = "Boman | Privacy Policy"
  end

  def CncMachining
    @page_title = "Boman | CNC Machining"
  end

  def ProductionEquipment
    @page_title = "Boman | Production Equipment"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contact/new.html.erb
<div class="container">

  <div class="contact-header">
    <h1>Contact Us! <i class="far fa-handshake handshake"></i></h1>
    <p class="text-muted">We're happy to answer any of your questions and provide an estimate. Whether the requirement is one part or one hundred thousand, we can make it. Send us a challenge specifying the part details and any questions you might have!</p>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="contact-cards">
        <h3>Made In America.</h3>
        <hr>
        <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d24009.193835996237!2d-73.09460691755655!3d41.218518335107234!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89e874af6c0f7d6f%3A0x628fe866f5989806!2s67+Erna+Ave%2C+Milford%2C+CT+06461!5e0!3m2!1sen!2sus!4v1533431084498" width="100%" height="500" frameborder="0" style="border:0" allowfullscreen></iframe>
        <div class="contact-info">
          <h6>Contact Us:</h6>
          <div class="social-icons display-inline-block">
            <a href="mailto:sales@bomantechnologies.com?subject=Reaching out from the website" target="_blank" "email me"><i class="fas fa-envelope-open-text envelope"></i></a>
            <i class="fas fa-phone phonecontact" data-toggle="tooltip" data-placement="right" title="203-415-8350"></i>
          </div>
          <hr>

          <h6>Social:</h6>
          <div class="social-icons display-inline-block">
            <a href="https://www.facebook.com/Boman-Technologies-707644796260330/" target="_blank"><i class="fab fa-facebook-square"></i></a>
            <a href="https://twitter.com/BomanTech" target="_blank"><i class="fab fa-twitter"></i></a>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-6">
      <div class="contact-cards">
        <h3>Give us a challenge!</h3>
        <hr>
        <%= form_for @contact, url: create_contact_url do |f| %>
        <!-- <p id="notice"><%= notice %></p> -->
        <p id="errors"><%= @contact.errors.full_messages.join(", ") %></p>
        <div class="form-group">
          <label>Name</label>
          <%= f.text_field :name, class: 'control', maxlength: 35 %>
        </div>

        <div class="form-row">
          <div class="form-group col-md-6">
            <label>Email</label>
            <%= f.text_field :email, class: 'control', maxlength: 30 %>
          </div>
          <div class="form-group col-md-6">
            <label>Phone</label>
            <%= f.text_field :phone, class: 'control phone_us', maxlength: 20 %>

          </div>
        </div>

        <div class="form-group">
          <label>Job Position</label>
          <%= f.text_field :job_position, class: 'control', maxlength: 50 %>
        </div>
     
        <div class="form-group">
          <label>Company Name</label>
          <%= f.text_field :company_name, class: 'control', maxlength: 50 %>
        </div>
      
        <div class="form-group">
           <%= f.text_area :body, placeholder: 'Describe your challenge!', rows: '10', maxlength: 1500, class: 'control contact-textarea', id: 'contactBodyId' %>
        </div>

        <div class="form-group">
          <% flash.each do |type, e| %>
            <div class="alert alert-info recaptcha-color"> <!-- change alert color? -->
              <%= e %>
            </div>
          <% end %>
          <%= recaptcha_tags %>
        </div>
        
        <!-- <div class="g-recaptcha recaptcha" data-sitekey="6LfrId8ZAAAAADfkdpDohP622YLAJTvRSvDc3uuj"></div>
        <br/> -->

        <div class="submit-btn display-inline-block">
          <span><%= f.submit 'Send', class: 'btn btn-primary' %></span>
          <span id="characterCounter" class="text-muted"><span id="charsRemaining">1500</span> Characters remaining</span>
        </div>
      </div>
    </div>

  </div>
</div>

<% end %>

<script type="text/javascript">
  $(document).ready(function(){
    var count;

    function countCharacters(e) {
      var textEntered, countRemaining, counter;
      textEntered = document.getElementById('contactBodyId').value;
      counter = (1500 - (textEntered.length));
      countRemaining = document.getElementById('charsRemaining');
      countRemaining.textContent = counter;
    }

    count = document.getElementById('contactBodyId');
    count.addEventListener('keyup', countCharacters, false);
  })
</script>

<script type="text/javascript" src="https://embed.modernapp.co/chat?code=9dae6c8c94e76fbf61ca0571e6d49fed"></script>

<script>
    $(document).ready(function(){
        $('[data-toggle="tooltip"]').tooltip();   
    });
</script>

<script type="text/javascript">
  $(document).ready(function(){
    $('.phone_us').mask('(000) 000-0000');
  })
</script> 

<script type="text/javascript">
  $(document).on "turbolinks:load", ->
  alert "page has loaded!"

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title> <%= @page_title %> </title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Crimson+Text:600|Headland+One|Source+Serif+Pro:600|Tenor+Sans|Tinos|Varela" rel="stylesheet">
    <%= csrf_meta_tags %>

    <meta name="keywords" content="<%= @seo_keywords %>">
    <!-- <script src="https://www.google.com/recaptcha/api.js" async defer></script> -->
    <%= stylesheet_link_tag    'pages', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= render "shared/nav_header" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/AboutUs.html.erb
<div class="jumbotron jumbotron-fluid jumbotron-au">
  <div class="aboutUs-text">
    <h1 class="aboutUs-header">About Us</h1>
    <span class="aboutUs-subText">We focus on building engineering partnerships with our clients. At Boman, we evolve in lockstep with you to meet your most demanding engineering issues. We can make the technological machining investments necessary for your products to be produced efficiently and cost effectively.</span>
  </div>
</div>

<div class="aboutUs-container">
  <div class="team-header">
    <h1>Meet the Team</h1>
    <p class="text-muted">A wealth of experience and a drive to deliver the highest quality products.</p>
  </div>

  <div class="row">
    <div class="col-md-4">
      <div class="card aboutMe-card">
        <%= image_tag("bird.jpg",  alt: "Alan", class: "card-img-top") %>
        <div class="card-body">
          <h5 class="card-title">Alan Godman</h5>
          <p class="card-text"><small class="text-muted">President, CEO</small></p>
          <p class="card-text">In 1994 Alan assumed ownership of Boman Tool upon his father's retirement. He directed the company toward the future – computer controlled machinery and the new, Boman Precision Technologies was born.</p>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="card aboutMe-card">
        <%= image_tag("sailboat.jpg",  alt: "Mike", class: "card-img-top") %>
        <div class="card-body">
          <h5 class="card-title">Michael Richmond, BSME</h5>
          <p class="card-text"><small class="text-muted">Senior Production Engineer</small></p>
          <p class="card-text">Mike is a graduate of NYU Polytechnic. With five years of experience in design and production his focus is on our Cincom Swiss machines and supervising production. When not programming he can be found building beautiful wooden boats.</p>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="card aboutMe-card">
        <%= image_tag("Donna2.jpg",  alt: "Donna", class: "card-img-top") %>
        <div class="card-body">
          <h5 class="card-title">Donna Rhoads-Frost, MSc</h5>
          <p class="card-text"><small class="text-muted">Director of Operations</small></p>
          <p class="card-text">Donna combines 20 years of project management and operational experience in the aviation, environmental and educational fields to grow Boman’s Advanced Manufacturing footprint. Her expertise includes analytical analysis and optimization. She is also developing a STEM internship program at Boman.</p>
        </div>
      </div>
    </div>
  </div>


                            <!-- Adam Behuniak,  adam-behuniak.jpg--> 
  <div class="row">
    <div class="col-md-4">
      <div class="card aboutMe-card">
        <%= image_tag("adam-behuniak.jpg",  alt: "Adam", class: "card-img-top flip-image") %>
        <div class="card-body">
          <h5 class="card-title">Adam Behuniak</h5>
          <p class="card-text"><small class="text-muted">Production Coordinator</small></p>
          <p class="card-text">Adam is one of Boman's longest standing members. His wealth of knowledge and versatility is crucial to day to day operations. He supports every aspect of production and is integral to QA/QC operations. </p>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="card aboutMe-card">
        <%= image_tag("marcus.jpg",  alt: "Marcus", class: "card-img-top flip-image") %>
        <div class="card-body">
          <h5 class="card-title">Marcus Chadwick</h5>
          <p class="card-text"><small class="text-muted">Senior Production Technician</small></p>
          <p class="card-text">Marcus mainly runs production and oversees the progress of our bigger orders. He provides efficent engineering with a keen eye for quality inspection. He is currently developing our Miyano department to be better than ever!</p>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="card aboutMe-card">
        <%= image_tag("linus.jpg",  alt: "Linus", class: "card-img-top") %>
        <div class="card-body">
          <h5 class="card-title">Linus</h5>
          <p class="card-text"><small class="text-muted">Morale Officer</small></p>
          <p class="card-text">Easily the best looking boy on the team! Linus has been with us for 2 years and he keeps spirits high!</p>
        </div>
      </div>
    </div>
  </div>
</div>


<script type="text/javascript" src="https://embed.modernapp.co/chat?code=9dae6c8c94e76fbf61ca0571e6d49fed"></script>

app/views/pages/CncMachining.html.erb
<div class="jumbotron jumbotron-fluid jumbotron-cnc">
  <!-- <div class="cnc-cover-box"> -->
    <div class="cnc-cover-text">
      <!-- <h1 class="CNC-header">CNC Machining</h1> -->
      <!-- <span class="aboutUs-subText">We focus on building engineering partnerships with our clients. At Boman, we evolve in lockstep with you to meet your most demanding engineering issues. </span> -->
    </div>
 <!--  </div> -->
</div>

<div class="cnc-container">
  <div class="cnc-p-header">
    <h1>Prototypes</h1>
    <!-- <p class="text-muted">A wealth of experience and a drive to deliver the highest quality products.</p> -->
  </div>
  <div class="prototypes">
    <p>Boman Technologies can produce CNC prototype machined parts.<p>

    <p>Some of our clients need simply one production quality prototype part for proof of concept, visual testing or form fit and function while others need multiple parts for engineering testing or marketing studies. Regardless of your job volume, we are able to provide production quality parts in the same materials that the final product will be made from in a production environment.</p>
  </div>

  <div class="cnc-p-header">
    <h1>Small to Medium Lot Production</h1>
    <!-- <p class="text-muted">A wealth of experience and a drive to deliver the highest quality products.</p> -->
  </div>

  <div class="low-level-production">
    <p>Boman Technologies has the ability to produce CNC machined parts in small lot volumes. With multiple CNC machines and working to our client needs we are able to produce parts in higher volumes, meeting rapid delivery schedules at a high quality level. We are positioned to produce lots anywhere from 1 - 15,000 pieces per run.</p>
  </div>
  
  <div class="cnc-p-header">
    <h1>Materials</h1>
    <!-- <p class="text-muted">A wealth of experience and a drive to deliver the highest quality products.</p> -->
  </div>

  <div class="materials">
    <p>Boman has experience machining many types of plastics and metals. Below is a list of some of them.</p>
  </div>

  <div class="container materials-container">
    <div class="row">
      <div class="col">
        <ul>
          <li>Titanium</li>
          <li>Stainless Steel</li>
          <li>Brass 360, 464</li>
        </ul>
      </div>
      <div class="col">
        <ul>
          <li>A105</li>
          <li>Nickel</li>
          <li>Various Plastics</li>
        </ul>
      </div>
      <div class="col">
        <ul>
          <li>Tool Steel</li>
          <li>Carbon Steel</li>
          <li>Aluminium</li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/pages/HarrassmentPolicy.html.erb
<div class="container">
  <div id="har-Wrapper">
    <div id="pri_h1">
      <p class="har-title">Harassment Policy</p>
    </div>
    <p class="text-muted font-italic">Effective: January 1st, 2020</p>
    <p>Boman Technologies is committed to providing a work environment in which all workers are treated with respect and dignity. Workplace harassment will not be tolerated from any person in the workplace including customers, clients, other employers. </p>
    
    <div class="har-h3">
      <h3>What is Harassment?</h3>
    </div>

    <p>Workplace harassment means engaging in a course of vexatious comment or conduct against a worker in a workplace that is known or ought reasonably to be known to be unwelcome or workplace sexual harassment. Workplace sexual harassment means:</p>

    <ul id="har-bullet"><li id="har-list">Engaging in a course of vexatious comment or conduct against a worker in a workplace because of sex, sexual orientation, gender identity or gender expression, where the course of comment or conduct is known or ought reasonably to be known to be unwelcome.</li></ul>

    <ul id="har-bullet"><li id="har-list">Making a sexual solicitation or advance where the person making the solicitation or advance is in a position to confer, grant or deny a benefit or advancement to the worker and the person knows or ought reasonably to know that the solicitation or advance is unwelcome; 
    Reasonable action taken by the employer or supervisor relating to the management and direction of workers or the workplace is not workplace harassment.</li></ul>

    <p>Workers are encouraged to report any incidents of workplace harassment to the appropriate manager.</p>

    <p>Management will investigate and deal with all complaints or incidents of workplace harassment in a fair, respectful and timely manner. Information provided about an incident or about a complaint will not be disclosed except as necessary to protect workers, to investigate the complaint or incident, to take corrective action or as otherwise required by law.</p>

    <p>Managers, supervisors and workers are expected to adhere to this policy, and will be held responsible by the employer for not following it. Workers are not to be penalized or disciplined for reporting an incident or for participating in an investigation involving workplace harassment.</p>

    <div class="har-h3">
      <h3>More Information</h3>
    </div>

    <p>For more information refer to the state of Connecticut's sexual harassment page: <a id="har-link" href="https://www.cga.ct.gov/olm/docs/Sexual%20Harassment%20Policy%202018.pdf" target="_blank">Sexual Harassment Policy</a></p>

  </div>
</div>

app/views/pages/PrivacyPolicy.html.erb
<div class="container">
  <div id="privacyWrapper">
    <div id="privacy_h1">
      <p class="pri-title">Privacy Policy</p>
    </div>

    <p class="text-muted font-italic">Last Modified: October 6th, 2019</p>
    
    <p>At Boman Technologies one of our main priorities is the privacy of our visitors. This Privacy Policy document contains types of information that is collected and recorded by Boman Precision Technologies and how we use it.</p>

    <p>If you have additional questions or require more information about our Privacy Policy, do not hesitate to contact us through email at sales@bomantechnologies.com</p>
    
    <div class="pri-h3">
      <h3>Log Files</h3>
    </div>

    <p>Boman Technologies follows a standard procedure of using log files. These files log visitors when they visit websites. All hosting companies do this and is a part of the hosting services' analytics. The information collected by log files include internet protocol (IP) addresses, browser type, Internet Service Provider (ISP), date and time stamp, referring/exit pages, and possibly the number of clicks. These are not linked to any information that is personally identifiable. The purpose of the information is for analyzing trends, administering the site, and gathering demographic information. These tools we use do not obtain personal information about you and cannot obtain information from your hard drive or pass on a computer virus.</p>

    <div class="pri-h3">
      <h3>Cookies</h3>
    </div>

    <p>Like any other website, Boman Technologies uses 'cookies'. These cookies are used to store information including visitors' preferences, and the pages on the website that the visitor accessed or visited. The information is used to optimize the users' experience by customizing our web page content based on visitors' browser type and/or other information. When we collect personal information, it is only done with your knowledge (such as filling out the contact form). This personal information includes your name, email address, telephone number and what you say in the message field. All of this information is solely used to assist our customers and contact them promptly.</p>

    <p>Most modern browsers allow users to decide whether to accept cookies, so you have the choice to not use them or not on our site.</p>
    
    <div class="pri-h3">
      <h3>Online Privacy Policy Only</h3>
    </div>

    <p>This Privacy Policy applies only to our online activities and is valid for visitors to our website with regards to the information that they shared and/or collect in Boman Technologies. This policy is not applicable to any information collected offline or via channels other than this website.</p>
    
    <div class="pri-h3">
      <h3>Consent</h3>
    </div>
  
    <p>By using our website, you hereby consent to our Privacy Policy and agree to its Terms and Conditions. As upgrades are made to this site the Privacy Policy will be updated accordingly.</p>
  </div>
</div>

app/views/pages/ProductionEquipment.html.erb
<div class="jumbotron jumbotron-fluid jumbotron-pro">
  <!-- <div class="cnc-cover-box"> -->
    <div class="cnc-cover-text">
      <!-- <h1 class="CNC-header">CNC Machining</h1> -->
      <!-- <span class="aboutUs-subText">We focus on building engineering partnerships with our clients. At Boman, we evolve in lockstep with you to meet your most demanding engineering issues. </span> -->
    </div>
 <!--  </div> -->
</div>

<div class="cnc-container">
  <div class="cnc-p-header">
    <h1>Our Machines</h1>
    <!-- <p class="text-muted">A wealth of experience and a drive to deliver the highest quality products.</p> -->
  </div>
  <div class="production">
    <p>Boman Technologies specializes in machining standard and exotic metal parts and assemblies using state-of-the-art CNC turning, milling, and 5-axis centers. Years of experience provide expert knowledge of metal characteristics and how material groups react when machined. Tool selection, cutting pass depths, mill/lathe feed and speed, chip control, and high-pressure coolant are critical in controlling heat generation, which can cause part movement and tool deflection during the machining process. This level of skill ensures world-class precision machining that meets or exceeds the most demanding tolerances.</p>
  </div>

  <div class="pro-p-header">
    <h1>New Age</h1>
  </div>

  <div class="container production-container">
    <div class="row">
      <div class="col">
        <ul>
          <li>2020 VMC Mazak VCU400 HSK-63 high accuracy spindle 3 Axis. 20X-16Y-16Z 12000 RPM 25Hp Mitsubishi 780 control 0.0002 Volumetric accuracy</li>
          <li>2020 Wire EDM Mitsubishi 1200s, 12 RMA finish circuit. 16X-12Y-9Z Mitsubishi 800 control. 0.00001 accuracy</li>
          <li>2019 Grinder Acer 1020SGD 3 axis automatic</li>
          <li>2019 Swiss Citizen 20mm 11 axis 20LXi VDT (VDT for difficult-to-machine materials)</li>
          <li>2014 Turn-Mill 6-axis Miyano LZ-R2Y2 8” Chuck Fanuc 18T, 6-axis 6000 rpm Robotic Load/Unload</li>
          <li>2013 Turn-Mill 5-axis Miyano LZ-R2 8” Chuck Fanuc 18T, 5 Axis 6000 rpm Robotic Load/Unload</li>
          <li>2013 Turn-Mill 5-axis Miyano LZ-R1 Fanuc 6” Chuck OiT, 5 Axis 8000 rpm Robotic Load/Unload</li>
          <li>2005 Swiss 32mm Citizen 9 axis Lathe Mitsubishi 760 control Multiple Bar Loader</li>
          <li>2003 Swiss 20mm Swiss 10 axis lathe 20LVII Mitsubishi 740 control Multiple Bar Loader</li>
        </ul>
      </div>
    </div>
  </div>

  <div class="pro-p-header">
    <h1>Old Guard</h1>
  </div>

  <div class="container production-container">
    <div class="row">
      <div class="col">
        <ul>
          <li>1997 VMC Hardinge 700 4 axis Mill Fanuc 18M control (0.001 deg 4th axis)</li>
          <li>1998 Mill Turn, Super Precision HardingeT42SP 5 axis Lathe and bar feeder 0.00001 accuracy (ret)</li>
          <li>1997 Lathe, Super Precision Hardinge GT27SP 27mm 27mm lathe 0.00001 accuracy</li>
          <li>1996 Lathe, Super Precision Hardinge GT27SP 27mm Super Precision lathe, bar feeder 0.00001 accuracy</li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div id="footer" class="container-fluid">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <ul>
          <li><h6>Explore <i class="fas fa-globe-americas globe"></i></h6></li>
          <li class="footer-li"><%= link_to "Home", root_path %></li>
          <li class="footer-li"><%= link_to "About", about_us_path %></li>
          <li class="footer-li"><%= link_to "Contact", new_contact_path %></li>
          <li class="footer-li"><%= link_to "Privacy", privacy_policy_path %></li>
          <li class="footer-li"><%= link_to "Harassment Policy", harrassment_policy_path %></li>
        </ul>
      </div>

      <div class="col-md-4">
        <ul>
          <li><h6>Locally Made <i class="fas fa-location-arrow arrow"></i></h6></li>
          <li class="footer-li">Boman Precison Technologies</li>
          <li class="footer-li">67 Erna Avenue</li>
          <li class="footer-li">Milford, CT 06461</li>
        </ul>
      </div>
      
      <div class="col-md-4">
        <ul>
          <li><h6>Contact us <i class="fas fa-hands-helping hands"></i></h6></li>
          <li class="footer-li">sales@bomantechnologies.com</li>
          <li class="footer-li">Phone: 203.415.8350</li>
          <li class="footer-li">Fax: 203.877.3721</li>
        </ul>
          <!-- <script type="text/javascript">
          $('.hands').click(function(){ 
            alert("Call us: (203) 623-9119\r\nEmail our sales team: sales@bomantechnologies.com\r\nMessage us on Facebook!\r\nWe will respond as soon as we can.")
            ;}
          );
          </script> -->
      </div>
    </div>

    <div class="legal text-muted">
      <%= @copyright %>
    </div>
  </div>
</div>

app/views/shared/_nav_header.html.erb
<nav class="navbar sticky-top navbar-expand-lg navbar-light">
  <div class="logo">
    <%= link_to image_tag('Boman_logo.png'), root_path, id:"bowman_logo"%>
  </div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to 'Home', root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'About', about_us_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Contact', new_contact_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'CNC Machining', cnc_machining_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Production Equipment', production_equipment_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>